//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaProMaker.data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UI : global::System.Configuration.ApplicationSettingsBase {
        
        private static UI defaultInstance = ((UI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UI())));
        
        public static UI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ProjectAutomation\\TiaProMaker")]
        public string xmlFileFolder {
            get {
                return ((string)(this["xmlFileFolder"]));
            }
            set {
                this["xmlFileFolder"] = value;
            }
        }
    }
}
